services:
  
  redis:
    image: redis:7-alpine
    container_name: redis_url_shortener
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  
  mongo:
    image: mongo:6.0
    container_name: mongo_url_shortener
    ports:
      - "27017:27017"
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data:
